# Generated by Django 2.1.15 on 2021-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20210309_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stshortBIO',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
