# Generated by Django 2.2.5 on 2021-04-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_auto_20210403_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stPhotoPath',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stshortBIO',
        ),
    ]
