# Generated by Django 2.2.5 on 2021-04-03 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_auto_20210403_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
